name: wallpaper_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.1+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  file_picker: ^8.1.2
  flutter_image_compress: ^2.3.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.1.11
  flutter_local_notifications: ^17.2.3
  firebase_messaging: ^15.1.2
  firebase_core: ^3.5.0
  path_provider: ^2.1.4
  flutter_staggered_grid_view: ^0.7.0
  searchfield: ^1.0.3
  google_fonts: ^6.2.1
  glass_kit: ^4.0.1
  flutter_phone_direct_caller: ^2.1.1
  get: ^4.6.5  
  flutter_svg: ^2.0.5
  timeago: ^3.6.1
  rflutter_alert: ^2.0.7
  introduction_screen: ^3.1.14
  custom_sliding_segmented_control: ^1.8.3
  responsive_table: ^0.2.0+2
  get_storage: ^2.1.1
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.7.0
  bottom_sheet: ^4.0.0
  share_plus: ^10.0.2
  # audioplayers: ^6.0.0
  bootstrap_grid: ^1.0.4
  fl_chart: ^0.68.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  change_app_package_name: ^1.1.0
  flutter_cors: ^1.5.0
  
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/avatar/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
