// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMy7opv10Igsbb4eg8LE6KBgiPwo659_E',
    appId: '1:869513202326:web:21c17cbbf958064ea3d0b7',
    messagingSenderId: '869513202326',
    projectId: 'wallpaper-app-academy',
    authDomain: 'wallpaper-app-academy.firebaseapp.com',
    storageBucket: 'wallpaper-app-academy.appspot.com',
    measurementId: 'G-E0D5BCH19W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDINZRx8dHyvhow6bmrFqlDbybf6DpGxaY',
    appId: '1:869513202326:android:37745f2df334ad8fa3d0b7',
    messagingSenderId: '869513202326',
    projectId: 'wallpaper-app-academy',
    storageBucket: 'wallpaper-app-academy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf-35QSNXpN7ilvTO8QLIlCB68A22jj1M',
    appId: '1:869513202326:ios:43ee87433c439bdea3d0b7',
    messagingSenderId: '869513202326',
    projectId: 'wallpaper-app-academy',
    storageBucket: 'wallpaper-app-academy.appspot.com',
    iosBundleId: 'com.example.funSound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf-35QSNXpN7ilvTO8QLIlCB68A22jj1M',
    appId: '1:869513202326:ios:43ee87433c439bdea3d0b7',
    messagingSenderId: '869513202326',
    projectId: 'wallpaper-app-academy',
    storageBucket: 'wallpaper-app-academy.appspot.com',
    iosBundleId: 'com.example.funSound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMy7opv10Igsbb4eg8LE6KBgiPwo659_E',
    appId: '1:869513202326:web:887983f76b37c265a3d0b7',
    messagingSenderId: '869513202326',
    projectId: 'wallpaper-app-academy',
    authDomain: 'wallpaper-app-academy.firebaseapp.com',
    storageBucket: 'wallpaper-app-academy.appspot.com',
    measurementId: 'G-2SNSLW2HGH',
  );

}